FROM elixir:1.9.4-alpine

RUN apk add --no-cache --update nodejs npm
RUN mix do local.hex --force, local.rebar --force

WORKDIR /app

COPY mix.exs mix.lock ./
RUN MIX_ENV=test mix do deps.get, deps.compile
RUN MIX_ENV=prod mix do deps.get, deps.compile
